.PHONY: all

all:
	defaults write NSGlobalDomain AppleShowAllExtensions -bool true
	defaults write NSGlobalDomain KeyRepeat -int 2
	defaults write NSGlobalDomain InitialKeyRepeat -int 15
	defaults write NSGlobalDomain com.apple.mouse.scaling -float 3.0
	defaults write NSGlobalDomain com.apple.swipescrolldirection -bool true
	defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
	defaults write com.apple.finder ShowPathbar -bool true
