#!/hint/zsh

awsp() {
	local usage='Usage: awsp COMMAND

Commands:
	get		get current profile
	help		show usage
	list		show available profiles
	reset		reset to default profile
	set PROFILE	set profile'

	local config_file=${AWS_CONFIG_FILE:-$HOME/.aws/config}

	local cmd=$1
	case $cmd in
	get)
		print -r "${AWS_PROFILE:-default}"
		;;
	help | -h | --help)
		print -u2 "$usage"
		;;
	list)
		if [[ -f $config_file ]]; then
			sed -n -e 's/^\[default\]$/default/p' -e 's/^\[profile \(.*\)\]$/\1/p' "$config_file"
		fi
		;;
	reset)
		unset AWS_PROFILE
		;;
	set)
		if [[ -z $2 ]]; then
			print -u2 'awsp: requires an argument'
			return 1
		fi
		export AWS_PROFILE="$2"
		;;
	*)
		print -ru2 "awsp: unknown subcommand: '$cmd'"
		print -u2 "$usage"
		return 1
		;;
	esac
}

awsp "$@"
