#!/hint/zsh
# shellcheck disable=SC2034,SC2154,SC2206,SC2296,SC2298

zmodload zsh/zpty

osc2() {
	printf "\e]2;%s\e\\" "$*"
}

osc2_precmd() {
	if [[ -n $SSH_CONNECTION ]]; then
		osc2 "$(print -P '(%m) %1~:')" "-${SHELL:t}"
	else
		osc2 "$(print -P '%1~:')" "-${SHELL:t}"
	fi
}

osc2_preexec() {
	local cmd=(${(z)1})
	local j=1
	# skip all env vars
	while [[ ${cmd[$j]} == *=* ]]; do
		((j++))
	done
	# resolve alias recursively
	local c=${cmd[$j]}
	while ((${+aliases[$c]})); do
		cmd=(${(z)aliases[$c]})
		if [[ $c == "${cmd[1]}" ]]; then
			break
		fi
		c=${cmd[1]}
	done

	if [[ -n $SSH_CONNECTION ]]; then
		osc2 "$(print -P '(%m) %1~:')" "${c:t}"
	else
		osc2 "$(print -P '%1~:')" "${c:t}"
	fi
}

osc7() {
	printf "\e]7;file://%s%s\e\\" "$HOST" "$(urlescape --allow=/ -- "$PWD")"
}

osc133_precmd() {
	local exit_code=$?
	printf "\e]133;D;%d\e\\" "$exit_code"
	printf "\e]133;A\e\\"
}

osc133_preexec() {
	printf "\e]133;C\e\\"
}

prompt_mytheme_git_prompt_handler() {
	local fd=$1
	local response
	if zpty -r git_prompt_task response 2>/dev/null && [[ -n $response ]]; then
		_GIT_PROMPT_RAW=$response
		_GIT_PROMPT=$_GIT_PROMPT_RAW
		zle reset-prompt
	fi
	zle -F "$fd"
	zpty -d git_prompt_task 2>/dev/null
}

# setup git prompt asynchronously
prompt_mytheme_precmd() {
	# early break if already processing
	if zpty -t git_prompt_task 2>/dev/null; then
		return
	fi
	# gray out during processing
	[[ -n $_GIT_PROMPT_RAW ]] && _GIT_PROMPT='%B%F{black}'"$_GIT_PROMPT_RAW"'%f%b'
	# run `__git_ps1` asynchronously
	zpty -b git_prompt_task "__git_ps1 '(%s)'" 2>/dev/null
	zle -F "$REPLY" prompt_mytheme_git_prompt_handler
}

# reset git prompt
prompt_mytheme_chpwd() {
	unset _GIT_PROMPT _GIT_PROMPT_RAW
	zpty -d git_prompt_task 2>/dev/null
}

prompt_mytheme_setup() {
	local prompt_line_1='[%B%F{magenta}%n@%m%f%b:%B%F{cyan}%1~%f%b]'
	local prompt_line_2='%# '

	local git_ps1_src
	case $OSTYPE in
	darwin*)
		if [[ -n $HOMEBREW_PREFIX ]] && [[ -x $HOMEBREW_PREFIX/bin/git ]]; then
			git_ps1_src=$HOMEBREW_PREFIX/opt/git/etc/bash_completion.d/git-prompt.sh
		else
			git_ps1_src=/Library/Developer/CommandLineTools/usr/share/git-core/git-prompt.sh
		fi
		;;
	linux*)
		if [[ -f /etc/debian_version ]]; then
			git_ps1_src=/usr/lib/git-core/git-sh-prompt
		else
			git_ps1_src=/usr/share/git/completion/git-prompt.sh
		fi
		;;
	esac

	if [[ -n $git_ps1_src ]] && [[ -r $git_ps1_src ]]; then
		# shellcheck disable=SC1090
		. "$git_ps1_src"
		# shellcheck disable=SC2016
		prompt_line_1+='${_GIT_PROMPT}'
		GIT_PS1_SHOWDIRTYSTATE=1
		GIT_PS1_SHOWUNTRACKEDFILES=1
		add-zsh-hook chpwd prompt_mytheme_chpwd
		add-zsh-hook precmd prompt_mytheme_precmd
		prompt_cleanup 'add-zsh-hook -D chpwd prompt_mytheme_chpwd'
		prompt_cleanup 'add-zsh-hook -D precmd prompt_mytheme_precmd'
	fi

	PROMPT=$prompt_newline$prompt_line_1$prompt_newline$prompt_line_2
	RPROMPT='[%B%F{yellow}%?%f%b]'

	# OSC 2
	add-zsh-hook precmd osc2_precmd
	add-zsh-hook preexec osc2_preexec
	prompt_cleanup 'add-zsh-hook -D precmd osc2_precmd'
	prompt_cleanup 'add-zsh-hook -D preexec osc2_preexec'

	# OSC 7
	add-zsh-hook chpwd osc7
	prompt_cleanup 'add-zsh-hook -D chpwd osc7'
	osc7

	# OSC 133
	PROMPT=$'%{\e]133;P;k=i\e\\%}'"$PROMPT"$'%{\e]133;B\e\\%}'
	PROMPT2=$'%{\e]133;P;k=s\e\\%}'"$PROMPT2"$'%{\e]133;B\e\\%}'
	RPROMPT=$'%{\e]133;P;k=r\e\\%}'"$RPROMPT"$'%{\e]133;B\e\\%}'
	add-zsh-hook precmd osc133_precmd
	add-zsh-hook preexec osc133_preexec
	prompt_cleanup 'add-zsh-hook -D precmd osc133_precmd'
	prompt_cleanup 'add-zsh-hook -D preexec osc133_preexec'

	prompt_opts=(cr percent sp subst)
}

prompt_mytheme_setup "$@"
