#!/hint/zsh

swflutter() {
	local CMDNAME=swflutter
	local usage="Usage: $CMDNAME COMMAND

Commands:
	get		show current version
	help		show usage
	list		show available versions
	set VERSION	switch to the specified version"

	local base_dir=~/.local/flutter

	local cmd=$1
	case $cmd in
	get)
		readlink "$base_dir/default"
		;;
	help | -h | --help)
		print -ru2 "$usage"
		;;
	list)
		local versions=($base_dir/*(N/))
		if [[ ${#versions} -gt 0 ]]; then
			print -rl "${versions[@]:t}"
		fi
		;;
	set)
		local newver=$2
		if [[ -z $newver ]]; then
			print -ru2 "$CMDNAME: missing version"
			return 1
		elif [[ ! -d $base_dir/$newver ]]; then
			print -ru2 "${CMDNAME}: unknown version: $newver"
			return 2
		fi
		rm -f "$base_dir/default"
		ln -sf "$newver" "$base_dir/default"
		;;
	*)
		print -ru2 "${CMDNAME}: unknown subcommand: $cmd"
		print -ru2 "$usage"
		return 1
		;;
	esac
}

swflutter "$@"
