#!/hint/zsh

swflutter() {
	local usage='Usage: swflutter COMMAND

Commands:
	get		show current version
	help		show usage
	list		show available versions
	set VERSION	switch to the specified version'

	local base_dir=~/.local/flutter

	local cmd=$1
	case $cmd in
	get)
		readlink "$base_dir/default"
		;;
	help | -h | --help)
		echo "$usage" >&2
		;;
	list)
		find "$base_dir" -mindepth 1 -maxdepth 1 -type d | sed 's@^.*/@@'
		;;
	set)
		local newver=$2
		if [[ ! $newver ]]; then
			echo 'swflutter: missing version' >&2
			return 1
		elif [[ ! -d $base_dir/$newver ]]; then
			echo "swflutter: unknown version: $newver" >&2
			return 2
		fi
		rm -f "$base_dir/default"
		ln -sf "$newver" "$base_dir/default"
		;;
	*)
		echo "swflutter: unknown subcommand: '$cmd'" >&2
		echo "$usage" >&2
		return 1
		;;
	esac
}

swflutter "$@"
