#!/hint/zsh

readonly CMDNAME=swtex

usage() {
	printf 'Usage: %s COMMAND

Commands:
	get		show current version
	help		show usage
	list		show available versions
	set VERSION	switch to the specified version
' "$CMDNAME"
}

swtex() {
	local base_dir=~/.local/texlive

	local cmd=$1
	case $cmd in
	get)
		readlink "$base_dir/default"
		;;
	help | -h | --help)
		usage >&2
		;;
	list)
		local versions=($base_dir/*(N/))
		versions=(${versions:#*/texmf-local})
		if [[ ${#versions} -gt 0 ]]; then
			printf '%s\n' "${versions[@]:t}"
		fi
		;;
	set)
		local newver=$2
		if [[ -z $newver ]]; then
			printf "%s: missing version\n" "$CMDNAME" >&2
			return 1
		elif [[ ! -d $base_dir/$newver ]]; then
			printf "%s: unknown version: %s\n" "$CMDNAME" "$newver" >&2
			return 2
		fi
		rm -f "$base_dir/default"
		ln -sf "$newver" "$base_dir/default"
		;;
	*)
		printf "%s: unknown subcommand: %s\n" "$CMDNAME" "$cmd" >&2
		usage >&2
		return 1
		;;
	esac
}

swtex "$@"
