include ../../config.mk

.PHONY: all
all:
	$(KWRITECONFIG) --file dolphinrc --group DetailsMode --key PreviewSize 16
	$(KWRITECONFIG) --file dolphinrc --group General --key RememberOpenedTabs --type bool false
